import { getHypotheses } from "@/lib/data";
import { formatDate, percent } from "@/lib/format";

export default function HypothesesPage() {
  const hypotheses = getHypotheses().sort((a, b) => b.priority - a.priority);

  return (
    <main className="page">
      <section className="masthead">
        <div>
          <p className="eyebrow">Working Theory</p>
          <h1>Hypothesis map</h1>
          <p className="lead">
            Active claims, retired claims, and research leads generated by the nightly loop.
          </p>
        </div>
      </section>
      <div className="grid">
        {hypotheses.map((hypothesis) => (
          <article className="hypothesis-card span-6" key={hypothesis.id}>
            <div className="status-row">
              <span className={hypothesis.status === "weakened" ? "pill red" : "pill green"}>
                {hypothesis.status}
              </span>
              <span>{formatDate(hypothesis.updatedAt)}</span>
              <span>Priority {percent(hypothesis.priority)}</span>
            </div>
            <h3>{hypothesis.statement}</h3>
            <div className="confidence" aria-label={`Confidence ${percent(hypothesis.confidence)}`}>
              <span style={{ width: percent(hypothesis.confidence) }} />
            </div>
            {hypothesis.rationale ? <p className="prose">{hypothesis.rationale}</p> : null}
          </article>
        ))}
      </div>
    </main>
  );
}
